package com.pxf.project.springboottest.mybatis.model;

public class UserAuthIdSymbolKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column console_user_auth_id_symbol.SYMBOL_ID
     *
     * @mbggenerated
     * 标识ID
     */
    private String symbolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column console_user_auth_id_symbol.TENANT_ID
     *
     * @mbggenerated
     * 租户ID
     */
    private String tenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column console_user_auth_id_symbol.SYMBOL_ID
     *
     * @return the value of console_user_auth_id_symbol.SYMBOL_ID
     *
     * @mbggenerated
     */
    public String getSymbolId() {
        return symbolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column console_user_auth_id_symbol.SYMBOL_ID
     *
     * @param symbolId the value for console_user_auth_id_symbol.SYMBOL_ID
     *
     * @mbggenerated
     */
    public void setSymbolId(String symbolId) {
        this.symbolId = symbolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column console_user_auth_id_symbol.TENANT_ID
     *
     * @return the value of console_user_auth_id_symbol.TENANT_ID
     *
     * @mbggenerated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column console_user_auth_id_symbol.TENANT_ID
     *
     * @param tenantId the value for console_user_auth_id_symbol.TENANT_ID
     *
     * @mbggenerated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }
}