package com.pxf.project.springboottest.mybatis.model;

import java.util.Date;

public class UserAuthIdSymbol extends UserAuthIdSymbolKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column console_user_auth_id_symbol.AUTH_ID
     *
     * @mbggenerated
     * 通行证ID
     */
    private String authId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column console_user_auth_id_symbol.IDENTIFIERS
     *
     * @mbggenerated
     * 标识编号
     */
    private String identifiers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column console_user_auth_id_symbol.IDENTIFY_KIND
     *
     * @mbggenerated
     * 标识类型 0:用户名、1:手机、2:邮箱、3:QQ、4:微博、5:微信
     */
    private String identifyKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column console_user_auth_id_symbol.ID_STATUS
     *
     * @mbggenerated
     * 标识状态
     */
    private String idStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column console_user_auth_id_symbol.CREATE_TIME
     *
     * @mbggenerated
     * 创建日期
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column console_user_auth_id_symbol.CREATOR
     *
     * @mbggenerated
     * 创建人
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column console_user_auth_id_symbol.UPDATE_TIME
     *
     * @mbggenerated
     * 修改日期
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column console_user_auth_id_symbol.MODIFIER
     *
     * @mbggenerated
     * 修改人
     */
    private String modifier;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column console_user_auth_id_symbol.AUTH_ID
     *
     * @return the value of console_user_auth_id_symbol.AUTH_ID
     *
     * @mbggenerated
     */
    public String getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column console_user_auth_id_symbol.AUTH_ID
     *
     * @param authId the value for console_user_auth_id_symbol.AUTH_ID
     *
     * @mbggenerated
     */
    public void setAuthId(String authId) {
        this.authId = authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column console_user_auth_id_symbol.IDENTIFIERS
     *
     * @return the value of console_user_auth_id_symbol.IDENTIFIERS
     *
     * @mbggenerated
     */
    public String getIdentifiers() {
        return identifiers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column console_user_auth_id_symbol.IDENTIFIERS
     *
     * @param identifiers the value for console_user_auth_id_symbol.IDENTIFIERS
     *
     * @mbggenerated
     */
    public void setIdentifiers(String identifiers) {
        this.identifiers = identifiers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column console_user_auth_id_symbol.IDENTIFY_KIND
     *
     * @return the value of console_user_auth_id_symbol.IDENTIFY_KIND
     *
     * @mbggenerated
     */
    public String getIdentifyKind() {
        return identifyKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column console_user_auth_id_symbol.IDENTIFY_KIND
     *
     * @param identifyKind the value for console_user_auth_id_symbol.IDENTIFY_KIND
     *
     * @mbggenerated
     */
    public void setIdentifyKind(String identifyKind) {
        this.identifyKind = identifyKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column console_user_auth_id_symbol.ID_STATUS
     *
     * @return the value of console_user_auth_id_symbol.ID_STATUS
     *
     * @mbggenerated
     */
    public String getIdStatus() {
        return idStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column console_user_auth_id_symbol.ID_STATUS
     *
     * @param idStatus the value for console_user_auth_id_symbol.ID_STATUS
     *
     * @mbggenerated
     */
    public void setIdStatus(String idStatus) {
        this.idStatus = idStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column console_user_auth_id_symbol.CREATE_TIME
     *
     * @return the value of console_user_auth_id_symbol.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column console_user_auth_id_symbol.CREATE_TIME
     *
     * @param createTime the value for console_user_auth_id_symbol.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column console_user_auth_id_symbol.CREATOR
     *
     * @return the value of console_user_auth_id_symbol.CREATOR
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column console_user_auth_id_symbol.CREATOR
     *
     * @param creator the value for console_user_auth_id_symbol.CREATOR
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column console_user_auth_id_symbol.UPDATE_TIME
     *
     * @return the value of console_user_auth_id_symbol.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column console_user_auth_id_symbol.UPDATE_TIME
     *
     * @param updateTime the value for console_user_auth_id_symbol.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column console_user_auth_id_symbol.MODIFIER
     *
     * @return the value of console_user_auth_id_symbol.MODIFIER
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column console_user_auth_id_symbol.MODIFIER
     *
     * @param modifier the value for console_user_auth_id_symbol.MODIFIER
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }


    @Override
    public String toString() {
        return "UserAuthIdSymbol{" +
                "authId='" + authId + '\'' +
                ", identifiers='" + identifiers + '\'' +
                ", identifyKind='" + identifyKind + '\'' +
                ", idStatus='" + idStatus + '\'' +
                ", createTime=" + createTime +
                ", creator='" + creator + '\'' +
                ", updateTime=" + updateTime +
                ", modifier='" + modifier + '\'' +
                '}';
    }
}