package com.pxf.project.springboottest.mybatis.mapper;

import com.pxf.project.springboottest.mybatis.model.UserAuthIdSymbol;
import com.pxf.project.springboottest.mybatis.model.UserAuthIdSymbolExample;
import com.pxf.project.springboottest.mybatis.model.UserAuthIdSymbolKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserAuthIdSymbolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user_auth_id_symbol
     *
     * @mbggenerated
     */
    int countByExample(UserAuthIdSymbolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user_auth_id_symbol
     *
     * @mbggenerated
     */
    int deleteByExample(UserAuthIdSymbolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user_auth_id_symbol
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(UserAuthIdSymbolKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user_auth_id_symbol
     *
     * @mbggenerated
     */
    int insert(UserAuthIdSymbol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user_auth_id_symbol
     *
     * @mbggenerated
     */
    int insertSelective(UserAuthIdSymbol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user_auth_id_symbol
     *
     * @mbggenerated
     */
    List<UserAuthIdSymbol> selectByExample(UserAuthIdSymbolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user_auth_id_symbol
     *
     * @mbggenerated
     */
    UserAuthIdSymbol selectByPrimaryKey(UserAuthIdSymbolKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user_auth_id_symbol
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserAuthIdSymbol record, @Param("example") UserAuthIdSymbolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user_auth_id_symbol
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserAuthIdSymbol record, @Param("example") UserAuthIdSymbolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user_auth_id_symbol
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserAuthIdSymbol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table console_user_auth_id_symbol
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserAuthIdSymbol record);
}